site_name: Python BigQuery ORM
repo_name: FernandoCelmer/python-bigquery-orm
repo_url: https://github.com/FernandoCelmer/python-bigquery-orm
site_url: https://fernandocelmer.github.io/python-bigquery-orm/

nav:
    - Python BigQuery ORM: index.md

theme:
    name: simple-blog
    logo: assets/google_bigquery.png
