site_name: Python BigQuery ORM
repo_name: FernandoCelmer/python-bigquery-orm
repo_url: https://github.com/FernandoCelmer/python-bigquery-orm
site_url: https://fernandocelmer.github.io/python-bigquery-orm/
copyright: Fernando Celmer

nav:
  - Home: index.md
  - Release Notes: nav/release-notes.md

theme:
  name: material
  logo: assets/google_bigquery.png
  favicon: assets/google_bigquery.png

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - codehilite
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/FernandoCelmer
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/fernando-celmer/