site_name: Python BigQuery ORM
repo_name: FernandoCelmer/python-bigquery-orm
repo_url: https://github.com/FernandoCelmer/python-bigquery-orm
site_url: https://fernandocelmer.github.io/python-bigquery-orm/
copyright: Fernando Celmer

nav:
  - Home:
    - Overview: nav/home/index.md
    - Changelog: nav/home/changelog.md
    - Licence: nav/home/license.md
  - API reference:
    - API reference: nav/reference/index.md
  - Development:
    - Coverage report: coverage.md

theme:
  name: material
  logo: assets/google_bigquery.png
  favicon: assets/google_bigquery.png
  features:
  - navigation.footer
  - navigation.tabs

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.snippets:
      check_paths: true

extra_css:
  - stylesheets/extra.css

plugins:
- coverage

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/FernandoCelmer
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/fernando-celmer/
